/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Award = IDL.Record({
  'won' : IDL.Bool,
  'title' : IDL.Text,
  'year' : IDL.Nat,
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'bio' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'awards' : IDL.Vec(Award),
});

export const idlService = IDL.Service({
  'addAward' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAwards' : IDL.Func([], [IDL.Vec(Award)], ['query']),
  'getBio' : IDL.Func([], [IDL.Text], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getPortfolioByName' : IDL.Func([IDL.Text], [Portfolio], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'initializePortfolios' : IDL.Func([], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBio' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Award = IDL.Record({
    'won' : IDL.Bool,
    'title' : IDL.Text,
    'year' : IDL.Nat,
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'bio' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'awards' : IDL.Vec(Award),
  });
  
  return IDL.Service({
    'addAward' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAwards' : IDL.Func([], [IDL.Vec(Award)], ['query']),
    'getBio' : IDL.Func([], [IDL.Text], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getPortfolioByName' : IDL.Func([IDL.Text], [Portfolio], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'initializePortfolios' : IDL.Func([], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateBio' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };